### ISSUE TITLE
IP Address setting cannot be Private

### ISSUE THREAD

**Issue by crbaker** [Azure/aci-deploy#3]
When the _ip-address_ setting is set to **Private** the deployment fails with the following error "The Value of IP Address must be either Public or Private".

I suspect this issue will be true for all other properties that have either or options such as _os-type_, _protocol_, _restart-policy_.

**Comment by jakep36** [comment]
I'm having this issue as well.

**Comment by jakep36** [comment]
I think this will always throw an error if `ipAddress != 'Public'` https://github.com/Azure/aci-deploy/blob/5eddcdad28f81a886b87667828cda942ee91d11f/src/taskparameters.ts#L71

I think something like `if(!(ipAddress == "Public" || ipAddress == "Private"))` would work. I'm not exactly sure how to contribute here. This seems to be the same pattern for the other params that have either options like @crbaker mentioned above.

When I try to use my fork as the action I got a `Failed to fetch Azure access token` error.

**Comment by kf6kjg** [comment]
Underlying bug also causes #17.

Looks like whomever wrote the initial code thought that `a != b && c` evaluated like `![b, c].includes(a)` instead of as it really does `(a != b) && (true)`...

**Comment by kanika1894** [comment]
If I am not wrong, https://github.com/Azure/aci-deploy/pull/43 this solves the issue, right?

**Comment by kanika1894** [comment]
@daliborsavanovic @crbaker jakep36
This has been fixed in the patch version. We'll soon update the major version as well.
Can you please verify if using aci-deploy@v1.1.1 solves the issue and works well?

**Comment by daliborsavanovic** [comment]
Hi @kanika1894,

Haven't tried new version, but I can see a flaw there also, you're missing network profile parameter..
I have fixed my own (forked) version of this and continued..

**Comment by kanika1894** [comment]
Hey @daliborsavanovic , can you please more context around the network profile parameter.
The intention behind having v1.1.1 was to fix https://github.com/Azure/aci-deploy/issues/17 and https://github.com/Azure/aci-deploy/issues/3. 
But as per my understanding, there is something else that needs to be included?

**Comment by chelnak** [comment]
Looks like this is still broken because there is a dependency on dns-name-label that can't be met if you want private ip.

**Comment by kanika1894** [comment]
@chelnak can you please create a separate issue for this? 
This seems like making a parameter optional based on a condition, which we can handle separately.
The fix for the conditions is rolled out using https://github.com/Azure/aci-deploy/pull/43

**Comment by chelnak** [comment]
Sure, will do. I put it here because I felt like it was a bit of a regression from the fix.
